/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#5700c9",
        "tertiary-fixed-dim": "#d1bcff",
        "surface-dim": "#10131a",
        "background": "#10131a",
        "surface-container-low": "#191c22",
        "outline-variant": "#3b494b",
        "tertiary-fixed": "#e9ddff",
        "primary-fixed-dim": "#00dbe9",
        "surface-tint": "#00dbe9",
        "surface-container-high": "#272a31",
        "on-surface-variant": "#b9cacb",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "surface-container-lowest": "#0b0e14",
        "primary-container": "#00f0ff",
        "tertiary-container": "#e1d2ff",
        "secondary-container": "#42474f",
        "on-background": "#e1e2eb",
        "on-secondary-container": "#b1b5bf",
        "on-secondary-fixed-variant": "#42474f",
        "on-error": "#690005",
        "outline": "#849495",
        "inverse-surface": "#e1e2eb",
        "on-primary": "#00363a",
        "surface": "#10131a",
        "surface-container": "#1d2026",
        "on-secondary-fixed": "#171c23",
        "on-tertiary": "#3c0090",
        "secondary-fixed-dim": "#c2c7d0",
        "secondary": "#c2c7d0",
        "inverse-on-surface": "#2e3037",
        "on-tertiary-container": "#7213ff",
        "primary": "#dbfcff",
        "primary-fixed": "#7df4ff",
        "secondary-fixed": "#dee2ec",
        "on-surface": "#e1e2eb",
        "surface-variant": "#32353c",
        "inverse-primary": "#006970",
        "on-primary-fixed-variant": "#004f54",
        "surface-container-highest": "#32353c",
        "on-primary-fixed": "#002022",
        "surface-bright": "#363940",
        "tertiary": "#faf3ff",
        "on-secondary": "#2c3138",
        "on-primary-container": "#006970",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#23005b"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-desktop": "40px",
        "container-max": "1440px",
        "gutter": "24px",
        "unit": "4px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "code-md": ["JetBrainsMono_500Medium"],
        "code-sm": ["JetBrainsMono_500Medium"],
        "body-sm": ["Inter_400Regular"],
        "headline-lg": ["HankenGrotesk_700Bold"],
        "label-caps": ["JetBrainsMono_700Bold"],
        "body-md": ["Inter_400Regular"],
        "headline-sm": ["HankenGrotesk_600SemiBold"],
        "display-lg": ["HankenGrotesk_800ExtraBold"]
      },
    }
  },
  plugins: [],
}
